<definitions name="HelloWorld" targetNamespace="urn:HelloWorld" xmlns:tns="urn:HelloWorld"  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">

  <types>
        <xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Test">
            <xsd:element name="dataType" type="xsd:integer" />
            <xsd:element name="getResponseValueETB" type="xsd:string" />
        </xsd:schema>
    </types>

<message name="ETB">
  <part name="requestValue" type="xs:string"/>
</message>

<message name="getResponseValueETB">
  <part name="responseValue" type="xs:string"/>
</message>

<portType name="currencyConverterPort">
  <operation name="ETB">
    <input message="tns:ETB"/>
    <output message="getResponseValueETB"/>
  </operation>
</portType>

<binding type="currencyConverterPort" name="b1">
   <soap:binding style="document"
   transport="http://schemas.xmlsoap.org/soap/http" />
   <operation name="ETB">
     <soap:operation soapAction="convertAction"/>
     <input><soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
     <output><soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
  </operation>
</binding>

<service name="Service">
<port name="currencyConverterPort" binding="b1">
<soap:address location = "http://myhost/bamToEurServer.php"/>
</port>
</service>
</definitions>