<definitions name="HelloWorld" targetNamespace="urn:HelloWorld" xmlns:tns="urn:HelloWorld"  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">

  <types>
        <xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Test">
            <xsd:element name="dataType" type="xsd:integer" />
            <xsd:element name="getResponseValueBTE" type="xsd:string" />
        </xsd:schema>
    </types>

<message name="BTE">
  <part name="requestValue" type="tns:dataType"/>
</message>

<message name="getResponseValueBTE">
  <part name="responseValue" type="tns:dataType"/>
</message>

<portType name="currencyConverterPort">
  <operation name="BTE">
    <input message="tns:BTE"/>
    <output message="tns:getResponseValueBTE"/>
  </operation>
</portType>

<binding type="tns:currencyConverterPort" name="b1">
   <operation name = "BTE" >
     <soap:operation soapAction="convertAction"/>
     <input><soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
     <output><soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
  </operation>
</binding>

<service name="Service">
<port name="currencyConverterPort" binding="tns:b1">
<soap:address location = "http://myhost/eurToBamServer.php"/>
</port>
</service>
</definitions>